### ISSUE TITLE
No operations defined in spec!

### ISSUE THREAD

**Issue by LfJohnVo** [arsmn/fiber-swagger#12]
I have this problem, when i run my server its everything ok, but a have this :C
![image](https://user-images.githubusercontent.com/32848900/122502224-d7b92080-cfbb-11eb-8a89-a2db3949a141.png)
![image](https://user-images.githubusercontent.com/32848900/122502242-df78c500-cfbb-11eb-882f-e35c9a347a8b.png)
![image](https://user-images.githubusercontent.com/32848900/122502251-e30c4c00-cfbb-11eb-8ec5-e4cd2f7583b6.png)

**Comment by jusso-dev** [comment]
Hey @LfJohnVo so the reason is because you are not passing another function to your fibre router method, which is decorated with swagger markup comments.

See this article for more information - https://levelup.gitconnected.com/creating-a-swagger-documented-go-web-server-in-two-easy-steps-59f1118bd247

Hope this helps!

**Comment by Macrow** [comment]
in your import block

```
import (
	"fmt"
	swagger "github.com/arsmn/fiber-swagger/v2"
	"github.com/gofiber/fiber/v2"
	...
        _ "your-project-name/docs" // <- this is important!!
        ...
) 
```
